### PR TITLE
Fix exception handling

### LINKED ISSUE #24: User exception is handled as internal error
Invalid config with `columns` set to string instead of array:
```
{
      "definition": {
        "component": "keboola.processor-create-manifest"
      },
      "parameters": {
        "delimiter": "\t",
        "enclosure": "",
        "incremental": false,
        "columns": "auto"
      }
    }
```

` "errorOutput": "[2018-07-31 10:49:17] CRITICAL: Keboola\\Component\\UserException:Invalid type for path \"root.parameters.columns\". Expected array, but got string`

Error https://connection.keboola.com/admin/utils/logs?file=2018/07/31/12/2018-07-31-12-51-37-5b603f393d468-exception

### PR DESCRIPTION
**Pull request by odinuv**
fixes https://github.com/keboola/processor-create-manifest/issues/24 and https://github.com/keboola/processor-create-manifest/issues/22

### CODE REVIEW

File: src/Component.php [hunk 1]
```diff
@@ -58,59 +59,62 @@ public function run(): void
...
+                    }
                 }
-                $csv = new CsvFile($detectFile, $manifest["delimiter"], $manifest["enclosure"]);
-                if ($parameters["columns_from"] === 'auto') {
-                    $manifest["columns"] = $this->fillHeader(array_fill(0, $csv->getColumnsCount(), ""));
-                } elseif ($parameters["columns_from"] === 'header') {
-                    $manifest["columns"] = $this->fillHeader($csv->getHeader());
-                }
+            } catch (\Keboola\Csv\Exception $e) {
+                throw new UserException('The CSV file is invalid ' . $e->getMessage());
```
Comment (tomasfejfar) [inline src/Component.php]: Chybí dvojtečka?

**Review by tomasfejfar — APPROVED** [review]
LGTM, jen ta dvojtečka

**Review by tomasfejfar — APPROVED** [review]
